# Generated by Django 5.0 on 2023-12-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_en',
            field=models.TextField(null=True, verbose_name='Product text'),
        ),
        migrations.AddField(
            model_name='product',
            name='about_hy',
            field=models.TextField(null=True, verbose_name='Product text'),
        ),
        migrations.AddField(
            model_name='product',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='Product text'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Product name'),
        ),
    ]
